---
title: "Data Compilation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
library(janitor)
library(openxlsx)
library(rstanarm)
library(ggdist)
library(broom.mixed)
library(ggthemes)
library(nycgeo)
library(sf)
```

```{r}
# table will be the starting framework containing the relevant subgroups so that
# I can join data across grades from their respective sheets from the Excel

table <- read_excel(path = "raw_data/NYC_GEOG_DIST_1.xlsx",
                    sheet = 3,
                    skip = 1) %>%
  clean_names() %>%
  select(subgroup)

# filepaths contains the list of paths needed to access the data of all 32
# districts

filepaths = list("raw_data/NYC_GEOG_DIST_1.xlsx",
                 "raw_data/NYC_GEOG_DIST_2.xlsx",
                 "raw_data/NYC_GEOG_DIST_3.xlsx",
                 "raw_data/NYC_GEOG_DIST_4.xlsx",
                 "raw_data/NYC_GEOG_DIST_5.xlsx",
                 "raw_data/NYC_GEOG_DIST_6.xlsx",
                 "raw_data/NYC_GEOG_DIST_7.xlsx",
                 "raw_data/NYC_GEOG_DIST_8.xlsx",
                 "raw_data/NYC_GEOG_DIST_9.xlsx",
                 "raw_data/NYC_GEOG_DIST_10.xlsx",
                 "raw_data/NYC_GEOG_DIST_11.xlsx",
                 "raw_data/NYC_GEOG_DIST_12.xlsx",
                 "raw_data/NYC_GEOG_DIST_13.xlsx",
                 "raw_data/NYC_GEOG_DIST_14.xlsx",
                 "raw_data/NYC_GEOG_DIST_15.xlsx",
                 "raw_data/NYC_GEOG_DIST_16.xlsx",
                 "raw_data/NYC_GEOG_DIST_17.xlsx",
                 "raw_data/NYC_GEOG_DIST_18.xlsx",
                 "raw_data/NYC_GEOG_DIST_19.xlsx",
                 "raw_data/NYC_GEOG_DIST_20.xlsx",
                 "raw_data/NYC_GEOG_DIST_21.xlsx",
                 "raw_data/NYC_GEOG_DIST_22.xlsx",
                 "raw_data/NYC_GEOG_DIST_23.xlsx",
                 "raw_data/NYC_GEOG_DIST_24.xlsx",
                 "raw_data/NYC_GEOG_DIST_25.xlsx",
                 "raw_data/NYC_GEOG_DIST_26.xlsx",
                 "raw_data/NYC_GEOG_DIST_27.xlsx",
                 "raw_data/NYC_GEOG_DIST_28.xlsx",
                 "raw_data/NYC_GEOG_DIST_29.xlsx",
                 "raw_data/NYC_GEOG_DIST_30.xlsx",
                 "raw_data/NYC_GEOG_DIST_31.xlsx",
                 "raw_data/NYC_GEOG_DIST_32.xlsx")
```


```{r, cache = TRUE, message = FALSE}
# Creating a function to compile the 32 files worth of data into one tibble

grade_proficiency <- function(filepaths, table){
  
  # Accessing data from all 32 NYC Districts

  for(i in 1:length(filepaths)){
    
    # Accessing data for the performance of grades 3-8 for every district grade
    # 3 starts on the second sheet of every Excel 
    
    # leaving out sheets 1 and 8 for irrelevant data
    
    for(grade in c(2,3,4,5,6,7,9,10,11,12,13,14)){
      
      # Will use grade_num to label the columns by respective grade and allow
      # for cleaner merging later with respective district data
      # Separating data on ELA tests and math tests with suffix in column name
      
      if(grade < 8){
        grade_num = paste("g", grade + 1, "_ela", sep = "")
      } else {
        grade_num = ifelse(grade == 8, "", paste("g", grade - 6, "_math", sep = ""))
      }
      
      # Accessing data from specific grade
      
      information <- read_excel(path = paste(filepaths[i]),
                                sheet = grade,
                                skip = 1) %>%
        clean_names() %>%
        
        # percent_13 contains the data of a grade for the percentage of each
        # racial group that scored "proficient" on the state exam
        
        select(subgroup, percent_13) %>%
        rename(!!grade_num := percent_13)
      
      if(grade == 2){
        current_table <- table %>%
          left_join(information, by = "subgroup") 
      } else {
        current_table <- current_table %>%
          left_join(information, by = "subgroup") 
      }

    }
    current_table <- current_table %>%
      mutate(district = paste(i)) %>%
      filter(subgroup %in% c("All Students", "American Indian or Alaska Native", "Asian or Native Hawaiian/Other Pacific Islander", "Black or African American",
                             "Hispanic or Latino", "White", "Multiracial"))
    
    if(i == 1){
      new_table <- current_table
    } else {
      new_table <- new_table %>%
        full_join(current_table)
    }
  }
  return(new_table)
}


data <- grade_proficiency(filepaths, table) %>%
  filter(across(everything(), ~ !grepl("—", .))) %>%
  filter(!subgroup == "Multiracial") %>%
  drop_na() %>%
  mutate_each(funs(as.numeric(gsub("%", "", ., fixed = TRUE))/100), -c(subgroup, district))

data
test_data <- data

data %>%
  filter(district == 1) %>%
  pivot_longer(cols = g3_ela:g8_math,
               names_to = c("grade", "test"),
               names_sep = "_",
               values_to = "proficiency") %>%
  mutate_each(funs(as.numeric(gsub("g", "", ., fixed = TRUE))), -c("subgroup", "test", "proficiency")) %>%
  group_by(grade) %>%
  mutate(avg_prof = mean(proficiency)) %>%
  ggplot(mapping = aes(x = grade, y = avg_prof * 100)) +
  geom_line()
  

```

```{r}
# Plotting average proficiency data by grade per district

data %>%
  
  # Recognizing -- values as NA
  
  filter(across(everything(), ~ !grepl("—", .))) %>%
  drop_na() %>%
  
  # Mutating percentage strings as doubles
  
  mutate_each(funs(as.numeric(gsub("%", "", ., fixed = TRUE))/100), -c(subgroup, district)) %>%
  group_by(district) %>%
  summarize_all(mean) %>%
  select(district:g8_ela, -subgroup) %>%
  pivot_longer(names_to = "grade_test",
               values_to = "proficiency",
               cols = -district) %>%
  # group_by(grade_test) %>%
  # summarize_all(mean) %>%
  # ungroup() %>%
  ggplot(mapping = aes(x = grade_test, y = proficiency, group = district)) +
  geom_point() +
  geom_line() + 
  labs(title = "Average proficiency on ELA tests by grade for each district",
       x = "Grade",
       y = "Proficiency") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1))

data
```


```{r}
# Finding how the average proficiency on tests by race group change over time
# and where it divulges from the average and from other race groups

data %>%
  
  # Recognizing -- values as NA
  
  filter(across(everything(), ~ !grepl("—", .))) %>%
  filter(!subgroup == "Multiracial") %>%
  drop_na() %>%
  
  # Mutating percentage strings as doubles
  
  mutate_each(funs(as.numeric(gsub("%", "", ., fixed = TRUE))/100), -subgroup) %>%
  group_by(subgroup) %>%
  summarize_all(mean) %>%
  select(subgroup:g8_ela) %>%
  ungroup() %>%
  mutate(subgroup = as.factor(subgroup)) %>%
  # Trying to pivot wider to have subgroups and consequent grade scores
  pivot_longer(names_to = "grade_test",
               values_to = "proficiency",
               cols = g3_ela:g8_ela) %>%
  ggplot(mapping = aes(x = grade_test,
                       y = proficiency,
                       group = subgroup,
                       color = subgroup)) +
  geom_line() +
  scale_x_discrete(labels = c("3", "4", "5", "6", "7", "8")) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Average Proficiencies on 2018 ELA Tests by Grade",
       subtitle = "",
       x = "Grade",
       y = "Proficiency",
       caption = "Source: ",
       fill = "Subgroup")
  
```

```{r}
test_data <- data %>%
  select(-district) %>%
  pivot_longer(cols = g3_ela:g8_math,
               names_to = "test",
               values_to = "proficiency")

deviation <- stan_glm(data = test_data,
                      formula = proficiency ~ subgroup,
                      family = gaussian,
                      seed = 3,
                      refresh = 0)
test_data
newobs = tibble(subgroup = c("All Students", "American Indian or Alaska Native","Asian or Native Hawaiian/Other Pacific Islander", "Black or African American", "Hispanic or Latino", "White", "All Students"))

pe <- posterior_epred(deviation,
                      newdata = newobs) %>% 
  as_tibble() %>%
  set_names(newobs$subgroup)

plot_data <- pe %>%
  pivot_longer(names_to = c("Subgroup"),
               values_to = "Proficiency",
               cols = everything()) %>%
  filter(!Subgroup == "All Students")
  
  

plot_3 <- plot_data %>%
  ggplot(aes(x = Proficiency, y = fct_reorder(Subgroup, Proficiency),
             fill = "black")) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  stat_slab() + 
  theme_light() +
  theme(legend.position = "none") +
  labs(title = "Looking at Race as an Indication of Performance on\nState Test Results",
       x = "Proficiency Rates",
       y = "",
       caption = "Source: NYSED (2018)",
       fill = "Subgroup")

plot_3
```
```{r}
data_3 <- data %>%
  select(-district) %>%
  pivot_longer(cols = g3_ela:g8_math,
               names_to = c("grade", "test"),
               names_sep = "_",
               values_to = "proficiency") %>%
  mutate_each(funs(as.numeric(gsub("g", "", ., fixed = TRUE))), -c("subgroup", "test", "proficiency"))


data_3_fit <- stan_glm(data = data_3,
                       formula = proficiency ~ grade*subgroup,
                       family = gaussian,
                       seed = 3,
                       refresh = 0)

grade <- c(3, 4, 5, 6, 7, 8)
subgroup <- c("All Students", "American Indian or Alaska Native","Asian or Native Hawaiian/Other Pacific Islander", "Black or African American", "Hispanic or Latino", "White", "All Students")

newobs_3 <- expand_grid(grade, subgroup) %>%
  mutate(names = paste(grade, subgroup, sep = "_"))

newobs_3
pe_3 <- posterior_epred(data_3_fit,
                      newdata = newobs_3) %>% 
  as_tibble() %>%
  set_names(newobs_3$names)

plot_data_3 <- pe_3 %>%
  pivot_longer(names_to = c("Grade", "Subgroup"),
               names_sep = "_",
               values_to = "Proficiency",
               cols = everything()) %>%
  filter(!Subgroup == "All Students")
plot_data_3

plot_data_3 %>%
  ggplot(aes(x = Proficiency, y = fct_reorder(Subgroup, Proficiency),
             fill = Grade)) +
  stat_slab() +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Expected Peformance on State Test Results\nOver Time",
       x = "Proficiency Rates",
       y = "",
       caption = "Source: NYSED (2018)") +
  theme_light()

data_3
data_3 %>%
  ggplot(mapping = aes(x = grade, y = proficiency, group = grade)) +
  geom_boxplot()
```

```{r}




```

```{r}
library(shiny)
library(tidyverse)
library(shinythemes)

# Define UI for application that draws a histogram
ui <- navbarPage(
    fluidPage(theme = shinytheme("united")),
    "How NYC Students of Different Racial Groups Perform Academically Over Time",
    tabPanel("Comparing Performance by Test",
             fluidPage(
                 titlePanel("Comparing Performance by Test"),
                 sidebarLayout(
                     sidebarPanel(
                         selectInput(
                             "test",
                             "Choose a 2018 Test",
                             choices = c("English Language Arts" = "ela", 
                                         "Math" = "math")
                         ),
                         width = 300),
                     
                     imageOutput("test_plot")))),
    
    tabPanel("Predictions", 
             titlePanel("Predicting Performance Over Time"),
             imageOutput("grade"),
             p("This model predicts how students of specific racial groups will perform on their benchmark tests over time by grade."),
             h3("Regression Table and Interpretation")),
    # gt_output("table1")),
    
    tabPanel("About", 
             titlePanel("About"),
             p("Hi, I'm Hana Kim, a freshman at Harvard College who enjoys data science!"),
             p("You can reach me at hana_kim@college.harvard.edu."),
             p("This is the link to my repository: https://github.com/hanarubykim/final-project.git"),
             h3("Data Sources"),
             p("Through the New York State Education Department, I collected academic data concerning the 2018 State Test results from the 32 school districts of NYC. Through the New York City Department of Education, I collected data on demographic breakdown for the 2017-2018 academic year, which correlates with the population being surveyed within the former source.")
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
    
    output$test_plot <- renderImage({
        ifelse(input$test == "ela",
               list(
                   src = "ela.png",
                   width = 500,
                   height = 500),
               list(
                   src = "math.png",
                   width = 500,
                   height = 500))

        deleteFile = FALSE
    })
    
    output$grade <- renderImage({
        list(src = "grade_prediction.png")
        deleteFile = FALSE
    })
    
}

# Run the application 
shinyApp(ui = ui, server = server)

```

```{r}
map_data <- data %>%
  filter(subgroup == "All Students")

nyc_boundaries(geography = "school") %>%
  left_join(map_data, by = c("school_dist_id" = "district")) %>%
  ggplot() +
  geom_sf(aes(fill = g8_ela * 100)) +
  scale_fill_viridis_c(option = "clarity") +
  labs(title = "Average District Proficiency For 8th Graders on ELA Examinations",
       subtitle = "The districts of the Bronx, a predominantly Black and Hispanic borough, appears to have the lowest percentages of proficiency.",
       caption = "Source: NYSED (2018) and NYC DOE (2018)",
       fill = "Percent Proficient") +
  theme_void()

nyc_boundaries(geography = "school") %>%
  left_join(map_data, by = c("school_dist_id" = "district")) %>%
  ggplot() +
  geom_sf(aes(fill = g8_math * 100)) +
  scale_fill_viridis_c(option = "clarity") +
  labs(title = "Average District Proficiency For 8th Graders on Math Examinations",
       subtitle = "The districts of the Bronx, a predominantly Black and Hispanic borough, appears to have the lowest percentages of proficiency.",
       caption = "Source: NYSED (2018) and NYC DOE (2018)",
       fill = "Percent Proficient") +
  theme_void()
```

```{r}
race_data <- read_excel(path = "raw_data/demographic-snapshot.xlsx",
           sheet = 4) %>%
  clean_names() %>%
  
  # Looking at the relevant 2017-2018 demographic data, which represents the
  # same students who took the 2018 test
  
  filter(year == "2017-18") %>%
  
  # Only need to see the district and percentages for each racial group
  
  select(administrative_district, percent_asian:percent_white) %>%
  
  # Removing the preceding "0" from districts 1-9 for easier joining of data
  
  mutate(administrative_district = ifelse(administrative_district < 10, sub('.', '', administrative_district), administrative_district))


nyc_boundaries(geography = "school") %>%
  left_join(race_data, by = c("school_dist_id" = "administrative_district")) %>%
  ggplot() +
  geom_sf(aes(fill = percent_black * 100)) +
  scale_fill_viridis_c(option = "clarity",
                       direction = -1)

race_map_data


```



```{r}
combined_data <- full_join(data, race_data, by = c("district" = "administrative_district")) %>%
  drop_na()

# From a scatterplot, we may be able to assume a relationship with academic
# proficiency performance by students across all racial  groups in relation to
# the racial makeup of their schools

combined_data %>%
  filter(!subgroup == "All Students") %>%
  ggplot(mapping = aes(x = percent_black, y = g8_math, 
                       color = subgroup)) +
  geom_point() +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Proficiency Percentages of Racial Subgroups Relative to Percentage of Black Students",
       subtitle = "For districts with higher percentages of Black students, there is a marked decrease in percentage of proficient students in subgroups that are predicted to have high percentages of proficiency.",
       x = "Percentage of Black Students in District",
       y = "Proficiency Rate of Subgroup",
       caption = "Sources: NYSED (2018) and NYC DOE (2018)",
       color = "Racial Subgroup") +
  theme_light() +
  geom_smooth(mapping = aes(group = subgroup), method = "lm", se = FALSE)


combined_data %>%
  filter(!subgroup == "All Students") %>%
  ggplot(mapping = aes(x = percent_white, y = g8_math, 
                       color = subgroup)) +
  geom_point() +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Proficiency Percentages of Racial Subgroups Relative to Percentage of Black Students",
       subtitle = "For districts with higher percentages of Black students, there is a marked decrease in percentage of proficient students in subgroups that are predicted to have high percentages of proficiency.",
       x = "Percentage of Black Students in District",
       y = "Proficiency Rate of Subgroup",
       caption = "Sources: NYSED (2018) and NYC DOE (2018)",
       color = "Racial Subgroup") +
  theme_light() +
  geom_smooth(mapping = aes(group = subgroup), method = "lm", se = FALSE)


# With this model, we can see whether or not the predominant racial makeup of a
# district actually does affect how students of a racial group perform within
# that district

fit_3 <- stan_glm(data = combined_data,
                      formula = g8_math ~ percent_black*subgroup,
                      family = gaussian,
                      seed = 3,
                      refresh = 0)

print(fit_3, detail = FALSE)


fit_3 %>%
  as_tibble() %>%
  mutate()










print(fit_3, detail = FALSE)

subgroup <- c("All Students", "American Indian or Alaska Native","Asian or Native Hawaiian/Other Pacific Islander", "Black or African American", "Hispanic or Latino", "White", "All Students")
predom_asian <- c(TRUE, FALSE)

newobs_3 <- expand_grid(subgroup, predom_asian) %>%
  mutate(names = paste(subgroup, predom_asian, sep = "_"))

pe_4 <- posterior_epred(fit_3,
                        newdata = newobs_3) %>%
  as_tibble() %>%
  set_names(newobs_3$names)

plot_data_4 <- pe_4 %>%
  pivot_longer(names_to = c("Subgroup", "Subgroup"),
               names_sep = "_",
               values_to = "Proficiency",
               cols = everything()) %>%
  filter(!Subgroup == "All Students")



library(gtsummary)
library(gt)

tbl_regression(fit_1, 
               intercept = TRUE,
               estimate_fun = function(x) style_sigfig(x, digits = 3)) %>%
  
  as_gt() %>%
  
  # Formatting the table neatly and intuitively
  
  tab_header(title = md("**Predicting Proficiency on State Exams**"),
             subtitle = "How Racial Subgroup Affects Predicted Academic Proficiency") %>%
  tab_source_note(md("Source: NYSED (2018)")) %>% 
  cols_label(estimate = md("**Parameter**"))

```

